version: "3.4"

services:

# POSTGRES
  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - './_ds/db:/var/lib/postgresql/data'
      - './db.init.sql:/docker-entrypoint-initdb.d/iniDb.sql'
    environment:
      - POSTGRES_PASSWORD=ochenSlojniy
